using System.Text;
using ModernNet.Libraries.Text;

Console.OutputEncoding = Encoding.UTF8;
Console.WriteLine("Write something, punk...");
var input = Console.ReadLine() ?? string.Empty;

// Converting to bytes
var bytes = TextHelper.ConvertToBytes(input);
Console.WriteLine($"Generated bytes: ({bytes.Length}): {BitConverter.ToString(bytes)}");

// Converting the converted value into a string, again.
var decoded = TextHelper.ConvertToString(bytes);
Console.WriteLine($"Decoded text: {decoded}");

// Save to file
const string filename = "sample.txt";
await TextHelper.CreateEncodedFile(filename, decoded);

// Read created file
await TextHelper.ReadEncodedFile(filename);

// Build a string based on an enumerable set of string
IEnumerable<string> values = [
    "A Set of strings",
    "Placed randomly",
    "Just kidding, LMAO"
];

var builtString = TextHelper.BuildString(values);
Console.WriteLine(builtString);